---

- name: Check state of /dev/fuse
  stat: path=/dev/fuse
  register: encfs_dev_fuse

## FIXME: This will not survive reboot? Still required?
- name: Fix /dev/fuse permissions
  file: path=/dev/fuse owner=root group=fuse mode=1660
  sudo: True
  when: encfs_dev_fuse is defined and
        (encfs_dev_fuse.stat.gid == 0 and encfs_dev_fuse.stat.woth != True)

- name: Get current user account
  set_fact:
    encfs_user: '{{ ansible_env.USER }}'
  when: (encfs_user is undefined) or (encfs_user is defined and not encfs_user)

- name: Add encfs user to fuse group when needed
  user:
    name: '{{ encfs_user }}'
    groups: 'fuse'
    append: True
  register: encfs_fuse_group_added
  sudo: True
  when: (encfs_user|d() != 'root')

- name: Inform user that he needs to relogin to be in the fuse group
  fail:
    msg: 'You need to log out and back in to enable "fuse" system group.'
  when: (encfs_fuse_group_added is defined and encfs_fuse_group_added.changed == True) and
        (ansible_connection == 'local')


